data:
  source_path: datasets/mipnerf360/bicycle
  scaffold_model: outputs/scaffold15k_mipnerf360/bicycle/point_cloud/iteration_15000
  model_path: outputs/bicycle_scaffold_codec
  images: images
  resolution: -1
  data_device: cpu
  eval: true
  lod: 0
  white_background: false

model:
  anchor_feat_channels: 32
  n_offsets: 10
  latent_context_channels: 24
  anchor_context_channels: 24
  expand_offset_entropy_hidden: true
  offset_coding_scale_init: 25.0
  position_scaling_coding_scale_init: 32.0
  gaussian_scaling_coding_scale_init: 32.0
  feat_coding_scale_init: 4.0
  physical_voxel_size: 0.001
  anchor_grid_size: 0.002
  anchor_latent_channels: 4
  anchor_latent_coding_scale_init: 4.0
  offset_mask_threshold: 0.4
  add_opacity_dist: true
  add_cov_dist: true
  add_color_dist: false

train:
  iterations: 45000
  seed: 0
  lambda_dssim: 0.2
  lambda_rate: 0.001
  scaling_regularization: 0.01
  adam_beta1: 0.9
  adam_beta2: 0.999
  codec_network_beta2: 0.999
  codec_network_eps: 1.0e-8
  feat_lr_init: 0.0075
  feat_lr_final: 0.0075
  offset_lr_init: 0.01
  offset_lr_final: 0.0004
  scaling_lr_init: 0.007
  scaling_lr_final: 0.007
  codec_lr_init: 0.001
  codec_lr_final: 0.0004
  codec_lr_warmup_steps: 2000
  anchor_latent_lr_init: 0.01
  anchor_latent_lr_final: 0.008
  offset_mask_lr_init: 0.0025
  offset_mask_lr_final: 0.0005
  coding_scale_lr_init: 0.01
  coding_scale_lr_final: 0.001
  coding_scale_grad_clip: 0.01
  codec_grad_clip: 0.1
  mlp_opacity_lr_init: 0.0002
  mlp_opacity_lr_final: 0.00002
  mlp_cov_lr_init: 0.004
  mlp_cov_lr_final: 0.004
  mlp_color_lr_init: 0.00065
  mlp_color_lr_final: 0.00005
  rd_start_iteration: 0
  position_scaling_ste_start: 10000
  anchor_latent_rate_warmup_steps: 2000
  geom_attr_rate_warmup_steps: 3000
  feat_rate_warmup_steps: 2000
  log_interval: 500
  eval_interval: 5000
  checkpoint_interval: 0
  periodic_test_views: null
  offset_mask_prune_iterations: [35000]
  preserve_optimizer_after_mask_pruning: [1]
  resume: null
  stop_iteration: null
