# include "config/scaffold15k_mipnerf360.yaml"
data:
  root: datasets/bungeenerf
  scene: amsterdam
  output_root: outputs/scaffold15k_bungeenerf
  lod: 30

model:
  # Estimate the voxel size from the initial point cloud and use it for both scales.
  physical_voxel_size: 0.0
  anchor_grid_size: 0.0
  grow_physical_size_factors: [128, 32, 8]
  grow_grid_size_factors: [128, 32, 8]
